### ISSUE TITLE
Heroku dead

### ISSUE THREAD

**Issue by robbiet480** [ben174/bart-crime#42]
@ben174 looks like Heroku died in the last few weeks, last tweet was 8/17/21 and I got an email yesterday saying failed to renew SSL. Can you take a look?

**Comment by ben174** [comment]
On it. Thanks bud.

**Comment by ben174** [comment]
Also just gave up as cofounder on something that I’ve been working on. Got
decent runway but looking for work again soon. Lmk if you can help.

**Comment by robbiet480** [comment]
@ben174 Just forwarded you an email from Heroku

**Comment by ben174** [comment]
On it. Gimme 30.
